CATEGORY_MAPPING = {
    'beer_festival' :   {
        "Top-up: Custom": "gate",
        "Top-up: £10": "gate",
        "Cans": "kicthen",
        "Scratchings": "kicthen",
        "Rolls": "kicthen",
        "Entry Ticket": "gate",
        "Samosa": "kicthen",
        "Entry Only": "gate",
        "Crisps": "kicthen",
        "Tea/ Coffee": "kicthen",
        "Black Pudding": "kicthen",
        "Single Burger": "bbq",
        "+ Cheese": "bbq",
        "Hot Dog": "bbq",
        "Double Burger": "bbq",
        "+ Bacon": "bbq",
        "Pork Pie": "kicthen",
        "Triple Burger": "bbq",
        "donation": "gate",
        "unknown": "gate",
        "Gift card": "gate",
        "10 Small Pots for £18 🪴": "XX",
        "5 Large Pots for £16 🏺": "XX",
        "Burger": "bbq",
        "Bacon Bap": "bbq",
        "Hot Drinks": "kicthen",
        "Custom": "gate",
        "Top Up Ticket": "gate",
        "Book of Beer": "gate",
    },

    'bedding_plant_sale' :  {
        "Tea/ Coffee": "kicthen",
        "donation": "none",
        "unknown": "none",
        "Gift card": "none",
        "Small Pot - Discounted": "small_pot",
        "Tomato - Discounted": "small_pot",
        "Tray - Discounted": "tray",
        "Hanging Basket - Discounted ": "basket",
        "Hanging Basket 🧺": "basket",
        "8 Trays for £22 📤": "tray",
        "1 Small Pot 🪴": "small_pot",
        "1 Tray 📤": "tray",
        "Tomato Plant 🍅": "small_pot",
        "10 Small Pots for £18 🪴": "small_pot",
        "5 Large Pots for £16 🏺": "large_pot",
        "1 Large Pot 🏺": "large_pot",
        "Burger": "food",
        "Large Pot 🏺": "large_pot",
        "Tray 📤": "tray",
        "Bacon Bap": "food",
        "Hot Drinks": "kicthen",
        "Custom": "none",
    },

    'coronation' :  {
        "Corrination Drinks": "none",
        "Raffle": "none",
        "Custom": "none",
    },

    'xmas_cheer' :  {
        "Tea/ Coffee": "kitchen",
        "donation": "none",
        "unknown": "none",
        "Gift card": "none",
        "Raffle": "raffle",
        "Bacon Bap": "kitchen",
        "Hot Drinks": "kicthen",
        "Custom": "none",
    },

    'other' :  {
        "donation": "none",
        "unknown": "none",
        "Gift card": "none",
        "Hall Hire": "Hall Hire",
        "Custom": "none",
    },
}
