UNIFIED_PRODUCT_MAPPING = {
    'beer_festival' :   {
        "Top-up: Custom": "topup_token",
        "Top-up: £10": "topup_token",
        "Cans": "can",
        "Scratchings": "scratching",
        "Rolls": "roll",
        "Entry Ticket": "entry_ticket",
        "Samosa": "samosa",
        "Entry Only": "entry_only",
        "Crisps": "crisps",
        "Tea/ Coffee": "hot_drink",
        "Black Pudding": "black_pudding",
        "Single Burger": "single_burger",
        "+ Cheese": "added_cheese",
        "Hot Dog": "hot_dog",
        "Double Burger": "double_burger",
        "+ Bacon": "added_bacon",
        "Pork Pie": "pork_pie",
        "Triple Burger": "triple_burger",
        "donation": "donation",
        "unknown": "topup_token",
        "Gift card": "gift_card",
        "Burger": "burger",
        "Bacon Bap": "bacon_bap",
        "Hot Drinks": "hot_drink",
        "Custom": "topup_token",
        "Top Up Ticket": "topup_token",
        "Book of Beer": "beer_book",
    },

    'bedding_plant_sale' :  {
        "Tea/ Coffee": "hot_drink",
        "donation": "donation",
        "unknown": "unknown",
        "Gift card": "gift_card",
        "Small Pot - Discounted": "small_pot",
        "Tomato - Discounted": "tomato",
        "Tray - Discounted": "tray",
        "Hanging Basket - Discounted ": "basket",
        "Hanging Basket 🧺": "basket",
        "8 Trays for £22 📤": "tray",
        "1 Small Pot 🪴": "small_pot",
        "1 Tray 📤": "tray",
        "Tomato Plant 🍅": "tomato",
        "10 Small Pots for £18 🪴": "small_pot",
        "5 Large Pots for £16 🏺": "large_pot",
        "1 Large Pot 🏺": "large_pot",
        "Burger": "burger",
        "Large Pot 🏺": "large_pot",
        "Tray 📤": "tray",
        "Bacon Bap": "bacon_bap",
        "Hot Drinks": "hot_drinks",
        "Custom": "unknown",
    },

    'coronation' :  {
        "Corrination Drinks": "none",
        "unknown": "unknown",
        "Gift card": "gift_card",
        "Raffle": "raffle",
        "Custom": "unknown",
    },

    'xmas_cheer' :  {
        "Tea/ Coffee": "hot_drinks",
        "donation": "donation",
        "unknown": "unknown",
        "Gift card": "gift_card",
        "Raffle": "raffle",
        "Bacon Bap": "bacon_bap",
        "Hot Drinks": "hot_drinks",
        "Custom": "unknown",
    },
}
